language: python
python:
  - "3.4"
before_install:
  - sudo apt-get install -y python3-dev python3-setuptools
  - sudo easy_install3 pip
  - sudo pip3 install pymongo
services:
  - mongodb
install: "pip install -r requirements.txt"
script: nosetests
